#!/bin/bash

function umountF(){
	sudo umount "$Dpath"
}

function writeF(){
	if [ "$ARG" == "FAT32" ]
	then
		sudo mkfs.fat -F32 -v -l "$Dpath"
	elif [ "$ARG" == "EXT4" ]
	then
		sudo mkfs.ext4 -F -O ^64bit -L '' "$Dpath"
	elif [ "$ARG" == "NTFS" ]
	then
		sudo mkfs.ntfs -Q -v -F -L '' "$Dpath"
	elif [ "$ARG" == "EMPTY" ]
	then
		sudo dd if=/dev/zero of="$Dpath" bs=512 count=1
	fi
}

function flashF(){
	sudo dd if="$Ipath" of="$Dpath" bs=4M conv=fdatasync
}

function checkF(){
	sudo fdisk -l
}

function helpF(){
	echo "

  [INFORMATION]
  
  -c: check devices.
  -p: the path of the device.
  -u: umount a device.
  -v: show the version of the script.
  
  [TO FORMAT THE DEVICE]
  
  -W: write the format to the usb table. (FAT32/EXT4/NTFS/EMPTY)
  
  [TO FLASH A IMAGE TO THE DEVICE]
  	
  -i: the path of the image.
  -F: flash a image into the device.
  
  REMEMBER: You need to use the uppercase flags (-W/-F) ever at the end!
	    Don't mix the Write and Flash commands!   
	    Use the main partition to describe it. The script will automatically write in the correct table.
	    Example:
	    
	    /dev/sdb
	    /dev/sdc
	    /dev/sde
	    ...
"
}

function versionF(){
	echo "  dwriter 1.2 - KanuX-14 | 07/19/2020 ~ 10:04 AM"
}

while getopts ":hcuFvtW:i:p:" opt; do
	case $opt in
	h) helpF
	;;
	c) checkF
	;;
	u) umountF
	;;
	i) Ipath="$OPTARG"
	;;
	p) Dpath="$OPTARG"
	;;
	W) ARG="$OPTARG"; writeF
	;;
	F) flashF
	;;
	v) versionF
	;;
	\?) helpF
	;;
	*) helpF
	;;
	esac
done
